### PR TITLE
Combined version for BG:EE and BGT

### PR DESCRIPTION
**Pull request by Roberciiik**
Highly experimental !!!

When reviewed, please select "hide whitespaces" options for better changes comparison. Please review as I could have missed something when applying changes.

Combined BG:EE (main) and BGT branches together. Tested installation on BG:EE, BG:SoD, BGT. I haven't run the game to test resources in-game.

### CODE REVIEW

**Comment by 11jo** [comment]
At first sight I don't see anything odd.

Do you plan to do other things like EET compatibility or further modifications. ?

I'm gonna do install tests and in game verifications before marked as reviewed.

Thanks for your work !

**Comment by Roberciiik** [comment]
> At first sight I don't see anything odd.

Good! Of course, I checked all the changes in the code, but I could have missed something.

> Do you plan to do other things like EET compatibility or further modifications. ?

After merging BGT with BG:EE I will repeat the same procedure with EET branch to keep only one code base branch.
I might add some minor improvements to code, nothing special before play.

**Review by 11jo — APPROVED** [review]
It's good for me. I let you merge the pull request as you like.

About merging after-EET branch, there is some compatibility changes made by EET [mentionned here](https://github.com/Gibberlings3/EET/tree/master/EET/compat/DarkHorizonsBGee). (Of course you know already about it)

I have implemented some of them in [this commit](https://github.com/The-Gate-Project/DarkHorizons/commit/0f17e209495ddb005822580bc2f825848f33face). (It's very minor.)
But I cannot remember if the items CMHAQ02 to CMSWQ14 have been corrected.

**Comment by Roberciiik** [comment]
> About merging after-EET branch, there is some compatibility changes made by EET [mentionned here](https://github.com/Gibberlings3/EET/tree/master/EET/compat/DarkHorizonsBGee). (Of course you know already about it)
> 
> I have implemented some of them in [this commit](https://github.com/The-Gate-Project/DarkHorizons/commit/0f17e209495ddb005822580bc2f825848f33face). (It's very minor.) But I cannot remember if the items CMHAQ02 to CMSWQ14 have been corrected.

I will take a look when merging.

**Pull request merged**
