### PR TITLE
Update several files

### PR DESCRIPTION
**Pull request by Lzw104522773**
Update the punctuation format of several files.

Update the tp2 file to avoid installation errors and avoid garbled prompts.

### CODE REVIEW

**Comment by 11jo** [comment]
But is this really enough to resolve the prompt thing ?

**Comment by Lzw104522773** [comment]
Just looking unhappy. It does not affect playing games.

After converting setup-ee.tra to UTF-8, the mod installation is complete and there will be no garbled dialog.tlk.

**Review by Roberciiik — APPROVED** [review]
This one looks fine. If you still want to update console prompts, please make a separated Pull Request and I will guide you how to update the prompt strings correctly without copying of the whole setup.tra file.

**Comment by 11jo** [comment]
@Lzw104522773 

The prompt issue appear for others mods or only DarkHorizons ?

Don't get me wrong, I want to understand why but if a workaround is needed it's ok.

@Roberciiik 

Thanks for your time.

**Comment by Lzw104522773** [comment]
When using the latest version of weiduexe, if setup.tra is encoded with ANSI, the prompt will be garbled. But this mod needs to transcode setup.tra to UTF-8, but if I encode setup.tra using UTF-8, the transcoded setup.tra will be garbled. So I added setup-osx.tra, setup-unix.tra, and setup-win32.tra (all using UTF-8 encoding) to avoid garbled prompts. This method has been adopted in other mods, such as bg1ub.

**Comment by Lzw104522773** [comment]
@0    = ~"Dark Horizons" Mod~
@1    = ~/****************************************~
@2    = ~* Dark Horizons Mod                     *~
@3    = ~* http://www.teambg.net                 *~
@4    = ~*  Copyright 2015 CoM_Solaufein         *~
@5    = ~*  THIS FILE WILL INSTALL               *~
@6    = ~* THE DARK HORIZONS IN YOUR GAME        *~
@7    = ~*      DIRECTORY.                       *~
@8    = ~*****************************************~
@9    = ~You do not appear to have BG:EE, EET, TotSC, TuTu or BGT installed.~

@890  = ~BG:EE install detected.~
@891  = ~Tutu install detected.~
@892  = ~BGT install detected.~
@893  = ~Please install on BG:EE, EET, TotSC, Tutu or BGT.~
@894  = ~BG1 install detected.~
@895  = ~EET install detected.~

I think it's okay to separate the above content in setup osx.tra, setup unix.tra, and setup win32.tra. Of course, for Chinese, that's Chinese.

**Comment by Roberciiik** [comment]
Generally speaking, Windows 10 console is printing characters in UTF-8. So to have correct localized names of components, you need to have UTF-8 encoded setup.tra file. So the proposed workaround from @Lzw104522773 is to create a second setup file with only UTF-8 encoded lines related to installation.

**Comment by Lzw104522773** [comment]
Yes，add setup-osx.tra, setup-unix.tra, and setup-win32.tra， It also does not affect the setup.tra of other languages.

**Comment by 11jo** [comment]
Yeah, I understand it's only for chinese.

So the issue is only for BGT since EE always load Setup-ee.tra ?

> This method has been adopted in other mods, such as bg1ub.

[It's not adopted yet.](https://github.com/Pocket-Plane-Group/bg1ub/pull/4)

And why three duplicated files are needed, only one can do the jobn no ?

**Comment by Roberciiik** [comment]
> So the issue is only for BGT since EE always load Setup-ee.tra ?

Unfortunately no, setup-ee.tra is loaded in later stage, after you click [Install] then weidu loads all components name. 

> And why three duplicated files are needed, only one can do the job, no ?

Potentially osx or linux console could have different encoding from Windows and therefore there are dedicated files for each operating system. 

> And if I understand correctly this garbled issue arise for every mods that have vanilla and EE compatibility ?

I would say that for every mod that uses ANSI encoding and not UTF. This is not related to EE in fact. Also this workaround could be implemented for all other languages but we in Polish, for example, skip special characters to print only English letters. It is harder for Chinese alphabet.

**Comment by Lzw104522773** [comment]
Add setup-osx.tra, setup-unix.tra, and setup-win32.tra， It is currently an effective method to solve the problem of garbled Chinese installation prompts. My friends: yoshimo0417 and MephistosataDevil, have already practiced on several mods.

**Comment by 11jo** [comment]
> Unfortunately no, setup-ee.tra is loaded in later stage, after you click [Install] then weidu loads all components name from setup ee file.

Oh, yes you right !

> Potentially osx or linux console could have different encoding from Windows and therefore there are dedicated files for each operating system.

Hum, don't understand that part, since only UTF8 can deal with symbole in prompt windows, but I don't have good knowledge about this.

> I would say that for every mod that uses ANSI encoding and not UTF. This is not related to EE in fact. Also this workaround could be implemented for all other languages but we in Polish, for example, skip special characters to print only English letters. It is harder for Chinese alphabet.

Ok, but this way is gonna be confusing for modders and translators, I think.

**Comment by GraionDilach** [comment]
> Potentially osx or linux console could have different encoding from Windows and therefore there are dedicated files for each operating system.

For Linux, that depends on $LANG. UTF-8 is mostly commonplace by now, but some server-oriented distros might fall back to ANSI for legacy terminal support.

**Comment by Roberciiik** [comment]
Many mods do a separation from install prompts and translation of items, scripts needed from setup file nowadays. We can see sometime file named "instal.tra", this is basically the same idea what @Lzw104522773 is trying to implement. 

@Lzw104522773 if all three files are encoded in UTF-8 anyway, can you simple add a single new file like install.tra with all lines required for translation?

**Comment by 11jo** [comment]
Hello Graion !

> Many mods do a separation from install prompts and translation of items, scripts needed from setup file nowadays. We can see sometime file named "instal.tra", this is basically the same idea what @Lzw104522773 is trying to implement.
> 
> @Lzw104522773 if all three files are encoded in UTF-8 anyway, can you simple add a single new file like install.tra with all lines required for translation?

Anyway we can do whatever you want for DarkHorizons but a method more common with other language could be nice.

**Comment by Roberciiik** [comment]
That's why I suggested having only a single install.tra file, that is optional, and other languages could implement it as well in the future.

**Comment by 11jo** [comment]
Yes, if @Lzw104522773 is willing to try your way maybe we can try to adapt it for other language too.

And it will provide a template of the method (though looking into mod with install.tra is already an exemple)

**Comment by 11jo** [comment]
It's funny but no matter how many mods I work on, encodage has been a pain to deal with, for each of them. Every time I think I definitly understand how it's work something new or odd arise !

**Comment by Lzw104522773** [comment]
Yes，we can.For the install.tra like：
QQ截图20240708194840
(Install.tra, using English as an example)
And tp2 fife is

LANGUAGE ~Simplified Chinese (Latest Chinese accent by YouYe)~
         ~Schinese~
         ~DarkHorizons/Language/Schinese/install.tra~

     If the installation prompt is placed in install.tra, the transcoding of Setup.tra can be ignored. This way, the installation prompt will not be garbled.

I have tested this method and the installation prompt will not be garbled. After installation, the dialog.tlk will also not be garbled.

For Chinese translators, this should be a relatively convenient solution and do not require too many changes to the TP2 file. If the installation prompt is in a separate file, taking this mod as an example, at most we can modify "ACTION_DEFINE_ARRAY charsetsNoConvertArray BEGIN setup-ee END" to "ACTION_DEFINE_ARRAY charsetsNoConvertArray BEGIN setup-ee install END". For other languages, this can also be done, and we need to conduct some testing

**Comment by Lzw104522773** [comment]
If we don't consider the operating system, we just need to add an install.tra that includes installation prompts.

**Comment by MephistoSatanDevil** [comment]
In fact, this is a historical issue. 
We are aware that there are multiple distribution versions of WeiDU. If we install a mod using an older version or the x86-legacy version, the setup.tra file needs to be encoded in ANSI; otherwise, it will appear as gibberish in the Windows console. 
However, we recently found that when using the latest version of WeiDU (WeiDU-Windows-249-amd64) for installation, the UTF8 Chinese characters can be displayed normally in the console without special settings when the default codepage is 936. Therefore, we adopted this method for translation, which is also the reason why Chinese translators sometimes updated the weidu.exe file when submitting translations a while ago.

Currently, when installing with the latest version of WeiDU, for the enhanced edition of the game, all tra files need to be encoded in UTF-8. Only for the original edition of the game, the game content part needs to be converted to ANSI encoding. However, since last year when we completed the Chinese localization work for SoD, both Chinese mod authors and players in the community have shifted to the enhanced edition and abandoned the original edition. Therefore, the simplest solution now is to convert all tra files to UTF-8 without any conversion, which will no longer cause encoding issues. As a result, but at the same time, we are not aware of the situation in other language communities, so we have adopted this method to avoid affecting other languages.

**Comment by Roberciiik** [comment]
> The only cost that needs to be paid is simply giving up support for the original version.

Yes, and I think we should not do this. There is large community that still use Original Baldur's Gate games and we don't want to cut them off from the latest updates of mods. Keeping multiple branches / repositories for EE and non-EE games are horrible for maintenance. 

So I am ok with a single optional install.tra file or event with the three setup-OS dependent files, unless it contains only the installation prompts.

**Comment by MephistoSatanDevil** [comment]
> > The only cost that needs to be paid is simply giving up support for the original version.
> 
> Yes, and I think we should not do this. There is large community that still use Original Baldur's Gate games and we don't want to cut them off from the latest updates of mods. Keeping multiple branches / repositories for EE and non-EE games are horrible for maintenance.
> 
> So I am ok with a single optional install.tra file or event with the three setup-OS dependent files, unless it contains only the installation prompts.


Perhaps using a setupEE.tra is indeed a very good option. or insstall.tra or whatever other name.

Alternatively, we could set development standards where all tra files are encoded in UTF-8, and only use WeiDU to convert them to ANSI encoding when installing the original edition. This approach would maintain compatibility with both the enhanced and original editions while simplifying the development and maintenance process.

**Comment by Roberciiik** [comment]
> Alternatively, we could set development standards where all tra files are encoded in UTF-8, and only use WeiDU to convert them to ANSI encoding when installing the original edition. This approach would maintain compatibility with both the enhanced and original editions while simplifying the development and maintenance process.

A lot of new mods are created this way, or even some older one are updated to be exclusively in UTF-8. However, here we are talking about older mod, that would benefit a bit less to make it rearranged of the translation files. Of course, if someone is willing to do so, and would do it correctly for all languages, I will be glad to merge such change. However, there were such examples like [here](https://github.com/Gibberlings3/The_Calling/pull/9), where such conversion failed for some languages, and then it created critical issue for the people of that country. 

So I think that adding additional file that works for Chinese is fine, and it is fast for you as translators. But of course, it's up to you guys.

**Comment by 11jo** [comment]
Yeah, keeping vanilla compatibility is mandatory for me too.

> Alternatively, we could set development standards where all tra files are encoded in UTF-8, and only use WeiDU to convert them to ANSI encoding when installing the original edition. This approach would maintain compatibility with both the enhanced and original editions while simplifying the development and maintenance process.

This way is interesting but I didn't found the courage to look at it yet...


And I may be wrong but both mentionned method (install.tra and native UTF8) will not help if player use an old or a legacy version of weidu, right ? (for EE or vanilla)

So if we don't keep a version of prompt without symbol those mentionned player will always have garbled prompts ?
And chinese player using an old or a legacy version of weidu will always got garbled prompt ?

**Comment by Lzw104522773** [comment]
> So I am ok with a single optional install.tra file or event with the three setup-OS dependent files, unless it contains only the installation prompts.

So,can I submit the PR as I mentioned above?

**Comment by Roberciiik** [comment]
> And I may be wrong but both mentionned method (install.tra and native UTF8) will not help if players use an old or a legacy version of weidu, right ? (for EE or vanilla)

From my understanding, this is true. However if any mod uses a newer version of WeiDU.exe then all older ones are updated to the latest you have. So this is the case if someone tries to install an ancient mod alone with prehistorical weidu version. But hey - if you are implementing this patch here, the newer version of Dark Horizon will use the latest weidu installer so only UTF-8 prompts should be used no matter how old other mods are. 

> So,can I submit the PR as I mentioned above?

Yes please, we will look at it.

**Comment by 11jo** [comment]
> From my understanding, this is true. However if any mod uses a newer version of WeiDU.exe then all older ones are updated to the latest you have. So this is the case if someone tries to install an ancient mod alone with prehistorical weidu version. But hey - if you are implementing this patch here, the newer version of Dark Horizon will use the latest weidu installer so only UTF-8 prompts should be used no matter how old other mods are.

It's probably unusual but until last years my computer was on windows XP so only legacy weidu was working to install mods.
In this case UTF8 is not enough.


Anyway thanks for the discussion and explanation everybody !

**Comment by MephistoSatanDevil** [comment]
> > From my understanding, this is true. However if any mod uses a newer version of WeiDU.exe then all older ones are updated to the latest you have. So this is the case if someone tries to install an ancient mod alone with prehistorical weidu version. But hey - if you are implementing this patch here, the newer version of Dark Horizon will use the latest weidu installer so only UTF-8 prompts should be used no matter how old other mods are.
> 
> It's probably unusual but until last years my computer was on windows XP so only legacy weidu was working to install mods. In this case UTF8 is not enough.
> 
> Anyway thanks for the discussion and explanation everybody !

For old computers and players of the original game, it may be necessary for them to perform some necessary manual operations, which would greatly simplify the difficulty of maintaining the mods.

**Comment by MephistoSatanDevil** [comment]
> > For old computers and players of the original game, it may be necessary for them to perform some necessary manual operations, which would greatly simplify the difficulty of maintaining the mods.
> 
> You're right, and probably not many players are in this situation.
> 
> In the french communauty we still encourage translators to avoid accent and symbol in prompts, but for chinese it's more complicated.
Yes, fortunately, the vast majority of Chinese players have now completely switched to the Enhanced Edition, so UTF-8 alone is perfectly normal. As a translator, as long as the mod code does not perform any special encoding conversions, there are no issues with the translation work.

**Comment by burner1024** [comment]
> For Linux, that depends on $LANG. UTF-8 is mostly commonplace by now, but some server-oriented distros might fall back to ANSI for legacy terminal support.

I think it is safe enough to assume that Linux and Mac consoles are UTF-8, whoever runs more exotic distros, or even BSD, can likely handle the charset issue.
But the draw of using `setup-%WEIDU_OS%` is to have different encodings. If they are the same, there's no point in that indeed.

> The only cost that needs to be paid is simply giving up support for the original version.

Hell no. I'll sooner drop support for EEs.

The main issue here, I think, is the lack of clarity from weidu side:
- not sure if `some integration into Windows that only newer OCaml provide` entails only console thing or something else.
- not sure on which windows versions does the newer weidu even run.
- not sure if this auto console encoding switch only happens for Chinese, or all languages. And on which windows versions.

Ultimately, if weidu drops legacy version, then mods will have to follow suit. If it doesn't, then why even have the newer one, it seems to just complicate things.

**Comment by Lzw104522773** [comment]
> But the draw of using `setup-%WEIDU_OS%` is to have different encodings. If they are the same, there's no point in that indeed.

MephistoSatanDevil solved the problem of garbled prompts when installing several mods in a Chinese environment using setup -% WEIDU-OS%. Of course, it only worked very well on Windows and has not been tested on other operating systems.After all, in China, the majority of players use my Windows.

**Comment by Lzw104522773** [comment]
@11jo @Roberciiik @GraionDilach 

I found that "Ding0's Quest Pack" is solved using setup -% WEIDUUOS%. tra.

https://www.pocketplane.net/quest-pack/

**Comment by Roberciiik** [comment]
Yes, it is a working solution. Since all files are in the UTF-8, I think there is no need to have separated 3 files for the console prompts.

**Comment by 11jo** [comment]
OSX and UNIX have the same encodage, but win32 is in ANSI.

Using %WEIDU_OS% requires us to add a file for each OS, even if they have the same encodage.

I was thinking but for chinese anyway, if the .tra files use GB2312 then prompt will be garbled no ?

**Comment by Roberciiik** [comment]
> Chinese and Russian for exemple will always be garbled on older weidu version whatever the file or encodage. And need to use another language for prompt. 

This is correct. Russian community has 3 different code pages for their consoles, and they agreed on using English names for components and to not translate any command prompts.

Using setup-%WEIDU_OS%.tra or install.tra in UTF-8 is always partial solution.

> Install.tra in UTF8 can be used even for vanilla game.

Yes, this is also true.

**Comment by 11jo** [comment]
Ok, thanks Roberciik !

If one day some chinese players complain about prompt because they are on older system, we could use the setup-%WEIDU_OS%.tra workaround with prompt in english for setup-win32.tra.

But according to Lzw104522773 and MephistoSatanDevil this is unlikely to be necessary.

**Comment by MephistoSatanDevil** [comment]
> If one day some chinese players complain about prompt because they are on older system, we could use the setup-%WEIDU_OS%.tra workaround with prompt in english for setup-win32.tra.
> 
> But according to Lzw104522773 and MephistoSatanDevil this is unlikely to be necessary.


Compared to the issues encountered with 'installation on the old system', the questions we are currently facing more are 'how to install mods on the phone'. So don't worry too much. XD

**Pull request merged**
