### PR TITLE
Unified Nikita's translation

### PR DESCRIPTION
**Pull request by Lzw104522773**
Unified Nikita's translation

### CODE REVIEW

**Comment by 11jo** [comment]
Hello !

Do you think the translation is complete, or do you have any other changes to commit ?

**Comment by Lzw104522773** [comment]
The Chinese version of the text I uploaded was translated by someone else, and I did not check it. Therefore, if a player discovers any errors in the text, I will promptly make corrections and submit a PR. So for some mods, I may submit Chinese translation files more frequently, especially for those mods that are not marked as translated by me. Please forgive me.

**Comment by 11jo** [comment]
I didn't mean it as a problem.

It's because I'm about to make a release in the next few days so I wanted to know if you had anything to add beforehand.

But you can always add corrections afterwards.

**Comment by Lzw104522773** [comment]
I haven't found any problems yet, so there are no issues at the moment.

**Pull request merged**
